workflows:
  build-main:
    name: Build
    instance_type: mac_mini
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - include: true
          pattern: develop
        - include: true
          pattern: hotfix/*
        - include: true
          pattern: release/*
    environment:
      xcode: latest
      groups:
        - app-store-connect
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Unshallow repository
        script: git fetch --unshallow
      - name: Initialize keychain
        script: keychain initialize
      - name: Fetch signing certificates
        script: app-store-connect fetch-signing-files $(xcode-project detect-bundle-id --target="Fyreplace Main") --type IOS_APP_STORE --create
      - name: Set up signing certificates
        script: keychain add-certificates
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Prepare files
        script: make
      - name: Install dependencies
        script: |
          brew install protobuf
          pod install
      - name: Build IPA
        script: xcode-project build-ipa --workspace Fyreplace.xcworkspace --scheme "Fyreplace Main"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
